{
  "formatVersion": "1.1",
  "component": {
    "group": "javard",
    "module": "javard",
    "version": "0.027-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.030-SNAPSHOT.jar",
          "url": "javard-0.030-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "7288a2f33a899202fc7260dc523360246d69a5c40da0d900cd47c2eb8cf29372127f45748a122ad0154a5d814bc8da3fa8b4512aa08ccf0bde8ad8d30ef64eac",
          "sha256": "0c0e6272ee9d5816d8fda090d9a72463c4bad05d6662d83edbe11262cba1c41c",
          "sha1": "97800d51044f582857f1ade942fc9f72c2b3ab29",
          "md5": "1225495a8e0153262e5b9f317ede20ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.030-SNAPSHOT.jar",
          "url": "javard-0.030-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "7288a2f33a899202fc7260dc523360246d69a5c40da0d900cd47c2eb8cf29372127f45748a122ad0154a5d814bc8da3fa8b4512aa08ccf0bde8ad8d30ef64eac",
          "sha256": "0c0e6272ee9d5816d8fda090d9a72463c4bad05d6662d83edbe11262cba1c41c",
          "sha1": "97800d51044f582857f1ade942fc9f72c2b3ab29",
          "md5": "1225495a8e0153262e5b9f317ede20ef"
        }
      ]
    }
  ]
}
